version: "3"
services:
  validator-1-11:
    container_name: validator-1-11
    build: "./miner"
    image: uhub.service.ucloud.cn/hard_docker/pyethapp-miner:0.5
    #image: localethereum/pyethapp-miner
    ports:
     - "192.168.0.97:30303:30303"
    volumes:
     - /root/docker-pyeth-dev/miner/start-validator.sh:/root/start.sh
     - /root/pyethereum:/ethereum/pyethereum
     - /root/pyethapp:/ethereum/pyethapp
     - /root/pydevp2p:/ethereum/pydevp2p
    environment:
      - BOOTSTRAP_NODE=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@192.168.0.120:30303
      - MINE_PERCENT=50
      - SLEEPTIME=1
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.20
networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.250.0/24
